# Generated by Django 3.1.1 on 2020-10-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
